### ISSUE TITLE
Id generation not working as intended

### ISSUE THREAD

**Issue by leopoldek** [SBUWebAndAppClub/ClubWebsite#1]
Id is supposed to be random but instead starts at 1 and increments by 1 for each new idea/project/member.

**Comment by murshidazher** [comment]
Yeah ID would be incrementing by one, bcoz its the primary key of the table. But we need an additional ID which is randomly generated by us and assigned to every user so we can make the url for them.

Ex  ID       Name  .... .... .... ...          _rID
      10      ABCD    .... .... .... ... ADRTY2546

Now _rID is the special random ID specified for the user ABCD. But the primary key ID is also needed so that the table knows whose random ID are we requesting for.

Now if we request the URL of user 10,
  Ex:- www.webdevclub.com/members/adrty2546.html

**Comment by edqu3** [comment]
Instead of storing an extra variable in the table for each entry, why not fetch the original ID from the database and then pass it through a hash function that will randomize the number (this will always output the same value).

for example:

id = 1 
output = hash(id)
// output = 3712EAFH2

id = 2 
output = hash(id)
// 1298120938

**Comment by leopoldek** [comment]
Issue fixed. Id is generated randomly and uniquely. Id is used in the URL to navigate to the item. See commit: a8e6675ab68d4a8e00dea4add67f0dae890cd6ba
